# -*- coding: utf-8 -*-
import sys

"""graph-dictionaryWD.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LAeO6qpKKHWzq7uCwT952r-BlIBeztl6

# Graph implementation using a Python dictionary

This implementation allows to represent any kind of graphs.
"""


class AdjacentVertex:
    """This class allows us to represent a tuple with an adjacent vertex
    and the weight associated (by default 1, for non-unweighted graphs)"""

    def __init__(self, vertex, weight=None):
        self._vertex = vertex
        self._weight = weight

    def __str__(self):
        if self._weight != None:
            return '(' + str(self._vertex) + ',' + str(self._weight) + ')'
        else:
            return str(self._vertex)


class Graph():
    def __init__(self, vertices, directed=True):
        """We use a dictionary to represent the graph
        the dictionary's keys are the vertices
        The value associated for a given key will be the list of their neighbours.
        Initially, the list of neighbours is empty"""
        self._vertices = {}
        for v in vertices:
            self._vertices[v] = []
        self._directed = directed

    def addEdge(self, start, end, weight=None):
        if start not in self._vertices.keys():
            print(start, ' does not exist!')
            return
        if end not in self._vertices.keys():
            print(end, ' does not exist!')
            return

        # adds to the end of the list of neigbours for start
        self._vertices[start].append(AdjacentVertex(end, weight))

        if self._directed == False:
            # adds to the end of the list of neigbours for end
            self._vertices[end].append(AdjacentVertex(start, weight))

    def containsEdge(self, start, end):
        if start not in self._vertices.keys():
            print(start, ' does not exist!')
            return 0
        if end not in self._vertices.keys():
            print(end, ' does not exist!')
            return 0

        # we search the AdjacentVertex whose v is end
        for adj in self._vertices[start]:
            if adj._vertex == end:
                if adj._weight != None:
                    return adj._weight
                else:
                    return 1  # unweighted graphs
        return 0  # does not exist

    def removeEdge(self, start, end):
        if start not in self._vertices.keys():
            print(start, ' does not exist!')
            return
        if end not in self._vertices.keys():
            print(end, ' does not exist!')
            return

        # we must look for the adjacent AdjacentVertex (neighbour)  whose vertex is end, and then remove it
        for adj in self._vertices[start]:
            if adj._vertex == end:
                self._vertices[start].remove(adj)
        if self._directed == False:
            # we must also look for the AdjacentVertex (neighbour)  whose vertex is end, and then remove it
            for adj in self._vertices[end]:
                if adj._vertex == start:
                    self._vertices[end].remove(adj)

    def __str__(self):
        result = ''
        for v in self._vertices:
            result += '\n' + str(v) + ':'
            for adj in self._vertices[v]:
                result += str(adj) + "  "
        return result

    def minDistance(self, visited, distance):

        min = sys.maxsize

        for i in self._vertices:
            for adj in self._vertices[i]:
                if visited[adj._vertex] == False and distance[adj._vertex] > min + adj._weight:
                    min = visited[adj._vertex]
                    min_vertex = adj._vertex

        return min_vertex

    def dijkstra(self, origin):
        if origin not in self._vertices.keys():
            return

        visited = {}
        distance = {}
        prev = {}

        for i in self._vertices.keys():
            visited[i] = False
            distance[i] = sys.maxsize
            prev[i] = None

        distance[origin] = 0

        for i in range(len(self._vertices)):
            u = self.minDistance(visited, distance)
            visited[u] = True
            for j in self._vertices[u]:
                if visited[j] is False and distance > distance[u] + j._weight:
                    distance[j] = distance[u] + j._weight
                    prev[j] = u

        return distance, prev


    def minimumPath(self, start, end):
        path = []

        distance, prev = self.dijktra(start)
        if start == end:
            pass
        elif distance[end] == sys.maxsize:
            pass
        else:
            last = prev[end]

            path.append(end)
            while last:
                path.insert(0,last)
                last = prev[last]
        return path











"""We use the implementation to represent an undirected graph without weights :


<img src='https://computersciencesource.files.wordpress.com/2010/05/dfs_1.png' width='35%'/>
"""
if __name__ == '__main__':
    labels = ['A', 'B', 'C', 'D', 'E']
    g = Graph(labels, False)
    g.addEdge('A', 'B')  # A:0, B:1
    g.addEdge('A', 'C')  # A:0, C:2
    g.addEdge('A', 'E')  # A:0, E:5
    g.addEdge('B', 'D')  # B:1, D:4
    g.addEdge('B', 'E')  # C:2, B:1
    # g.addEdge('A','H',8)

    print(g)

    """Now, we use the implementation to represent this graph: 

    <img src='https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/CPT-Graphs-directed-weighted-ex1.svg/722px-CPT-Graphs-directed-weighted-ex1.svg.png' width='25%'/>
    """

    labels = ['A', 'B', 'C', 'D', 'E']

    g = Graph(labels)

    # Now, we add the edges
    g.addEdge('A', 'C', 12)  # A->(12)C
    g.addEdge('A', 'D', 60)  # A->(60)D
    g.addEdge('B', 'A', 10)  # B->(10)A
    g.addEdge('C', 'B', 20)  # C->(20)B
    g.addEdge('C', 'D', 32)  # C->(32)D
    g.addEdge('E', 'A', 7)  # E->(7)A

    print(g)

    print(g.containsEdge('C', 'B'))

    print(g.containsEdge('B', 'C'))
    g.removeEdge('C', 'B')
    print(g)